### ISSUE TITLE
Can I also links different databases on the same server instance?

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/aras-homepage#1]
Hi Eli,

can this project also be used to access different databases on the same server instance?
In our internal trainings, we always work on a test database.

So far, I use the following link:
`http://---linktoplm---/?bypass_logon_form=false`

For me that's no problem, I have a lot of bookmarks in my browser.
But I have not yet found an elegant way to make it as easy as possible for new users to access the test database. Right now we use email links or bookmarks in our public training area. 

Best regards,
Angela

**Comment by EliJDonahue** [comment]
Hi Angela,

You should be able to specify the database in the query string like this:
```http://---linktoplm---/?database=DatabaseName```

Eli

>Note: This will only work for systems configured for Windows Authentication. It sounds like you do have WA enabled, but I just want to specify for anyone else who happens upon this thread.

**Comment by AngelaIp** [comment]
Nice! Didn´t know about the `?database` option. That makes a lot things easier.

**Comment by EliJDonahue** [comment]
It's buried in the Windows Authentication Setup documentation for Aras Innovator. 😄 Glad to help!
